name: "[Maintainers Only] Stage 2 - Create an Accepted Proposal"
description: "This template is reserved for Astro maintainers only."
body:
  - type: markdown
    attributes:
      value: |
        > **This template is reserved for Astro maintainers to officially accept existing discussions.**
        > You are probably looking to [**start a new discussion**](https://github.com/withastro/roadmap/discussions/new)!

        > To propose a new feature idea or enhancement, you should begin by creating a Discussion.
        > See the repo [`README.md`](https://github.com/withastro/roadmap#readme) for more info.
  - type: textarea
    id: main
    attributes:
      label: Details
      value: |
        - Accepted Date: <!-- today's date, YYYY-MM-DD -->
        - Reference Issues/Discussions: <!-- related issues, otherwise leave empty -->
        - Implementation PR: <!-- leave empty -->

        # Summary

        A brief, one or two sentence explanation of the proposal.

        # Background & Motivation

        Include any useful detail that that explains the background of this problem 
        at Astro and why this problem is worth solving. Why solve it now? Be brief!

        # Goals

        A **concise, bulleted-list** outlining the intended goals. 

        - What are the exact problems that you are trying to solve?
        - Avoid leading with a specific solution. Example: "Solve X" vs. "Solve X by doing Y"
        - Well-defined goals can lead to many alternative solutions!

        # Non-Goals 

        A **concise, bulleted-list** outlining anything intentionally left out as a goal:

        - Non-goal: A goal that is related, but intentionally avoided.
        - Out-of-scope: A goal that is related, but intentionally avoided due to scope.
        - Future: A goal that is related, but left to be addressed in the future.
        - It is okay to leave this section empty or N/A.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        > **Reminder: Stage 1 & 2 Proposals are just for the problem to solve.**
        > Want to discuss a specific solution? Comment after posting to kick off the convo!
